#include <string>
#include <vector>
#include <sstream>

//==============================================================================
// LeetCode #71: Simplify Path
// Implementation: Delimiter-Based Stream Tokenization via std::stringstream
//==============================================================================
/*
    Complexity Analysis:
    - Time Complexity: O(N) where N = path.length().
      - Traverses the character stream linearly to segment tokens by '/'.
      - Each directory segment is evaluated and pushed/popped in amortized O(1) time.
      - Canonical string reconstruction traverses the directory stack in O(K) where K <= N.
    - Auxiliary Space: O(N) auxiliary memory.
      - std::stringstream allocates an internal copy of the input string buffer.
      - 'dirStack' holds up to O(N) path component strings in dynamic heap storage.

    Algorithmic & POSIX File System Invariants:
    1. Root Anchoring Invariant:
       - Attempting to pop the parent directory ('..') from an empty stack is a safe no-op, 
         enforcing the POSIX invariant that the root directory '/' is its own parent.
    2. Identity & Redundancy Filtering:
       - Empty tokens generated by consecutive slashes ('//') and identity tokens ('.') 
         are skipped, normalizing redundant path separators.
    3. LIFO Directory Resolution:
       - A valid directory name is pushed onto the stack; '..' pops the most recent 
         directory, correctly resolving relative path traversals.

    Architectural Overhead & Optimization Vectors:
    - String Stream Overhead:
      - 'std::stringstream' and 'std::getline' trigger repeated dynamic heap allocations.
    - Zero-Copy In-Place Scanning:
      - Replacing stream extraction with an index-based two-pointer scan or 
        'std::string_view' slices operating on the original memory buffer drops 
        allocations to zero and lowers execution time to 0 ms.
*/
std::string simplifyPath(const std::string &path)
{
    std::stringstream ss(path);
    std::string token;
    std::vector<std::string> dirStack;

    while (std::getline(ss, token, '/'))
    {
        if (token.empty() || token == ".")
        {
            continue;
        }
        else if (token == "..")
        {
            if (!dirStack.empty())
            {
                dirStack.pop_back();
            }
        }
        else
        {
            dirStack.push_back(token);
        }
    }

    std::string simplifiedPath = "";
    for (const std::string &dir : dirStack)
    {
        simplifiedPath += ('/' + dir);
    }

    return (simplifiedPath.empty()) ? "/" : simplifiedPath;
}